### ISSUE TITLE
An exception occurred: KeyError: 'ip'

### ISSUE THREAD

**Issue by TravelTrexIT** [h4ndzdatm0ld/nautobot-ssot-vsphere#12]
### Environment
* Python version:  3.10
* Nautobot version:  1.3.6
* nautobot-ssot-vsphere version:  0.1.1

### Expected Behavior
The Job is running fine for a while and should update the Inventory for the updated Infrastructure.

### Observed Behavior
The scheduled job (also when i run it manually) creates this error message after a while:

```
Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 327, in run
    self.sync_data()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_vsphere/jobs.py", line 146, in sync_data
    vsphere_source.load()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_vsphere/diffsync/adapters/adapter_vsphere.py", line 220, in load
    self.load_data()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_vsphere/diffsync/adapters/adapter_vsphere.py", line 193, in load_data
    self.load_virtualmachines(cluster, diffsync_cluster)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_vsphere/diffsync/adapters/adapter_vsphere.py", line 64, in load_virtualmachines
    self.load_vm_interfaces(
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_vsphere/diffsync/adapters/adapter_vsphere.py", line 154, in load_vm_interfaces
    ipv4_addresses, ipv6_addresses = self.load_ip_addresses(
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_vsphere/diffsync/adapters/adapter_vsphere.py", line 84, in load_ip_addresses
    for ip_address in interface["ip"]["ip_addresses"]:
KeyError: 'ip'
```

### Steps to Reproduce
1. Run the Job initially and schedule it
2. Wait a time (some days)
3. The Job will fail creating a diff-change with the Keyerror 'ip'

**Comment by h4ndzdatm0ld** [comment]
Hi, thanks for checking out the project! Do you mind going to your vsphere API explorer or doing a curl on the troublesome VM, for guest/networking/interfaces? Share the output if you can. What version of vSphere are you using? Does this VM not have any interfaces?

Example: 

```bash
curl -X GET 'https://192.168.2.88/api/vcenter/vm/vm-1031/guest/networking/interfaces' -H 'vmware-api-session-id: 90e94549799ac544a42ab143fcc7f63f'
```

**Comment by TravelTrexIT** [comment]
Hi,

thanks for your response. Is there a possibility to see what is the corresponding VM which is doing trouble (i.e. the debug output for your Plugin)? Unfortunately i cannot see nothing in the logging except the printed error message from me.

**Comment by h4ndzdatm0ld** [comment]
Hi @TravelTrexIT could you install from git on branch `interfaces` and give it another try? Lets see if anything else comes up. Thanks - I will also work on adding some more debug output to better diagnose

**Comment by h4ndzdatm0ld** [comment]
Hey, thanks! Let me know if anything else comes up, happy to help! @TravelTrexIT
