### ISSUE TITLE
Job fails with `TypeError: string indices must be integers`

### ISSUE THREAD

**Issue by ggiesen** [h4ndzdatm0ld/nautobot-ssot-vsphere#16]
### Environment
* Python version:  3.8.12
* Nautobot version:  1.3.10
* nautobot-ssot-vsphere version:  0.2.5

### Expected Behavior
Import runs (dry run)

### Observed Behavior
```
Traceback (most recent call last):
  File "/opt/nautobot/lib64/python3.8/site-packages/nautobot_ssot/jobs/base.py", line 327, in run
    self.sync_data()
  File "/opt/nautobot/lib64/python3.8/site-packages/nautobot_ssot_vsphere/jobs.py", line 146, in sync_data
    vsphere_source.load()
  File "/opt/nautobot/lib64/python3.8/site-packages/nautobot_ssot_vsphere/diffsync/adapters/adapter_vsphere.py", line 218, in load
    self.load_data()
  File "/opt/nautobot/lib64/python3.8/site-packages/nautobot_ssot_vsphere/diffsync/adapters/adapter_vsphere.py", line 165, in load_data
    clustergroups = self.load_cluster_groups()
  File "/opt/nautobot/lib64/python3.8/site-packages/nautobot_ssot_vsphere/diffsync/adapters/adapter_vsphere.py", line 45, in load_cluster_groups
    self.get_or_instantiate(self.diffsync_clustergroup, {"name": clustergroup["name"]})
TypeError: string indices must be integers
```

### Steps to Reproduce
1. Run job (dry run)

**Comment by ggiesen** [comment]
Looks like this was a vSphere permissions issue. Closing
