### ISSUE TITLE
An exception occurred: KeyError: 'disks'

### ISSUE THREAD

**Issue by automate-this** [h4ndzdatm0ld/nautobot-ssot-vsphere#28]
### Environment
* Python version:  3.9
* Nautobot version:  1.4.5
* nautobot-ssot-vsphere version:  0.1.3

### Expected Behavior
Importing my VMs

### Observed Behavior
An exception occured

### Steps to Reproduce
1. Set up Nautobot
2. Import VMs
3. Profit

Detailed error Message:
```
Traceback (most recent call last):
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot/jobs/base.py", line 332, in run
    self.sync_data()
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_vsphere/jobs.py", line 146, in sync_data
    vsphere_source.load()
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_vsphere/diffsync/adapters/adapter_vsphere.py", line 223, in load
    self.load_data()
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_vsphere/diffsync/adapters/adapter_vsphere.py", line 195, in load_data
    self.load_virtualmachines(cluster, diffsync_cluster)
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_vsphere/diffsync/adapters/adapter_vsphere.py", line 61, in load_virtualmachines
    "disk": get_disk_total(virtual_machine_details["disks"]),
KeyError: 'disks'
```

Since I am not really sure which VM is affected, its hard finding out, since we have a few hundred of them.
Curling the API for a few VMs for the disks succeeded.

**Comment by h4ndzdatm0ld** [comment]
Hey there! Thanks for checking out the plugin! Will take a look and see what could be improved to handle this.

**Comment by h4ndzdatm0ld** [comment]
@automate-this  Can you install from the branch `bug/28/disks` and re-try? Let me know how that goes!

**Comment by automate-this** [comment]
Hey. Thanks for the quick reply. I am not really sure how to install the plugin from the branch into my docker containers.
I tried downloading the adapter_vsphere.py from the bug/28/disks branch and replaced it on all nautobot containers (/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_vsphere/diffsync/adapters/ ), but I still get the same error.

**Comment by automate-this** [comment]
Nevermind. I added a copy job to the Dockerfile and replaced the adapter_vsphere.py at build time.
Disks seem to run through, but now i get

```
An exception occurred: KeyError: 'power_state'

Traceback (most recent call last):
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot/jobs/base.py", line 332, in run
    self.sync_data()
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_vsphere/jobs.py", line 146, in sync_data
    vsphere_source.load()
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_vsphere/diffsync/adapters/adapter_vsphere.py", line 227, in load
    self.load_data()
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_vsphere/diffsync/adapters/adapter_vsphere.py", line 197, in load_data
    self.load_virtualmachines(cluster, diffsync_cluster)
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_vsphere/diffsync/adapters/adapter_vsphere.py", line 64, in load_virtualmachines
    "status": defaults.DEFAULT_VM_STATUS_MAP[virtual_machine_details["power_state"]],
KeyError: 'power_state'
```

**Comment by h4ndzdatm0ld** [comment]
New error, means progress! What vSphere version are you using? Seems like something that should be present in the response. Perhaps version change is not providing some of these results as expected in my api calls. 

Please share any vsphere information that could help me track that down

**Comment by automate-this** [comment]
I am using vSphere Version 7.0.3.00700

**Comment by automate-this** [comment]
If I understand correctly, the power_state API can return three states.
POWERED_OFF : The virtual machine is powered off.
POWERED_ON : The virtual machine is powered on.
SUSPENDED : The virtual machine is suspended.
https://developer.vmware.com/apis/vsphere-automation/latest/vcenter/data-structures/VM/Summary/

But you get only two states:
DEFAULT_VM_STATUS_MAP = CONFIG.get("VSPHERE_VM_STATUS_MAP", {"POWERED_OFF": "Offline", "POWERED_ON": "Active"})

Maybe thats it?

**Comment by automate-this** [comment]
Well it seems there was another problem after all. I ran into this bug:
https://kb.vmware.com/s/article/85053
Where vms with EFI return an error if you get the details via API.
So I edited all VMs that had EFI enabled, and saved them whithout making any changes.
After that the API call succeeded and your plugin also worked. (The one installed with pip )

**Comment by h4ndzdatm0ld** [comment]
@automate-this  That's great to hear. I think i'll add an option to track SUSPENDED state either way. So, you were able to do a full sync?

**Comment by automate-this** [comment]
Yes. It works now. Except for the duplicate name issue
