### ISSUE TITLE
Error if run job task

### ISSUE THREAD

**Issue by alvic2000** [h4ndzdatm0ld/nautobot-ssot-vsphere#48]
### Environment
* Python version:  3.9.16
* Nautobot version:  1.5.11
* nautobot-ssot-vsphere version:  0.1.4

### Expected Behavior
Job run without errors

### Observed Behavior
Job finished with error
An exception occurred: KeyError: 'value'

Traceback (most recent call last):
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot/jobs/base.py", line 332, in run
    self.sync_data()
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_vsphere/jobs.py", line 146, in sync_data
    vsphere_source.load()
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_vsphere/diffsync/adapters/adapter_vsphere.py", line 227, in load
    self.load_data()
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_vsphere/diffsync/adapters/adapter_vsphere.py", line 197, in load_data
    self.load_virtualmachines(cluster, diffsync_cluster)
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_vsphere/diffsync/adapters/adapter_vsphere.py", line 69, in load_virtualmachines
    self.load_vm_interfaces(
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_vsphere/diffsync/adapters/adapter_vsphere.py", line 158, in load_vm_interfaces
    ipv4_addresses, ipv6_addresses = self.load_ip_addresses(
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_vsphere/diffsync/adapters/adapter_vsphere.py", line 82, in load_ip_addresses
    for interface in vsphere_vm_interfaces.json()["value"]:
KeyError: 'value'
![image](https://user-images.githubusercontent.com/96197160/224997267-8c110e5d-032d-4ddf-8dce-d739b57e7e63.png)

Step before failed 
![image](https://user-images.githubusercontent.com/96197160/224997630-8904812e-d5dd-4401-949f-aec4d10ca0dc.png)

### Steps to Reproduce
1. Fresh nautobot installation.
2. Install nautobot-ssot-vsphere python package
3. Run job
Jobs - Jobs - SSoT - Virtualization ([VMWare vSphere ⟹ Nautobot]) - Run
![image](https://user-images.githubusercontent.com/96197160/225006462-008278e0-aeb0-4c57-b2c3-5c836795e1c6.png)

**Comment by h4ndzdatm0ld** [comment]
Hey, sorry completely missed this. Seems like an easy fix. Happy to accept a PR to handle this more gracefully. 

```
for interface in vsphere_vm_interfaces.json()["value"]:
KeyError: 'value'
```
