### ISSUE TITLE
Model class nautobot_ssot.models.Sync doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS

### ISSUE THREAD

**Issue by kagareu** [h4ndzdatm0ld/nautobot-ssot-vsphere#49]
### Environment
* Python version:  3.9.2
* Nautobot version:  1.5.18
* nautobot-ssot-vsphere version:  0.1.4

 nautobot service and worker service doesn't start

### Observed Behavior

Traceback (most recent call last):
  File "/scdata/nautobot/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/scdata/nautobot/lib/python3.9/site-packages/nautobot/core/cli.py", line 54, in main
    run_app(
  File "/scdata/nautobot/lib/python3.9/site-packages/nautobot/core/runner/runner.py", line 263, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/scdata/nautobot/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/scdata/nautobot/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/scdata/nautobot/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/scdata/nautobot/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/scdata/nautobot/lib/python3.9/site-packages/nautobot_ssot_vsphere/__init__.py", line 46, in ready
    super().ready()
  File "/scdata/nautobot/lib/python3.9/site-packages/nautobot/extras/plugins/__init__.py", line 149, in ready
    jobs = import_object(f"{self.__module__}.{self.jobs}")
  File "/scdata/nautobot/lib/python3.9/site-packages/nautobot/extras/plugins/utils.py", line 45, in import_object
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/scdata/nautobot/lib/python3.9/site-packages/nautobot_ssot_vsphere/jobs.py", line 14, in <module>
    from nautobot_ssot.jobs.base import DataMapping, DataSource
  File "/scdata/nautobot/lib/python3.9/site-packages/nautobot_ssot/jobs/__init__.py", line 7, in <module>
    from .base import DataSource, DataTarget
  File "/scdata/nautobot/lib/python3.9/site-packages/nautobot_ssot/jobs/base.py", line 24, in <module>
    from nautobot_ssot.models import Sync, SyncLogEntry
  File "/scdata/nautobot/lib/python3.9/site-packages/nautobot_ssot/models.py", line 39, in <module>
    class Sync(BaseModel):
  File "/scdata/nautobot/lib/python3.9/site-packages/django/db/models/base.py", line 113, in __new__
    raise RuntimeError(
RuntimeError: Model class nautobot_ssot.models.Sync doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

### Steps to Reproduce
install with last versions available

**Comment by kagareu** [comment]
i didn't see closed issue #32, sorry 
please add fix on your install instructions.
